# Generated by Django 3.2.19 on 2023-05-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20230525_1622'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
