# Generated by Django 3.2.19 on 2023-05-26 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
    ]
