# Generated by Django 3.2.19 on 2023-05-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'managed': False},
        ),
    ]
